uniflasher init

diff --git a/initramfs/init b/initramfs/init
--- a/initramfs/init
+++ b/initramfs/init
@@ -8,6 +8,52 @@ exec 1> /tmp/wz_mini_initramfs.log 2>&1
 /led.sh &
 led_pid="$!"
 
+check_prereq() {
+	command -v $1 > /dev/null && return
+	echo "Cannot find $1."
+	exit 1
+}
+
+uniflasher() {
+check_prereq dd
+check_prereq flashcp
+
+firmware="/sdcard/autoupdate-full.bin"
+if [ -z "$firmware" ]; then
+	echo "Usage: $0 <path to firmware file>"
+	exit 1
+fi
+
+# stop services
+killall majestic httpd ntpd crond || true
+
+mtd_num=0
+needle=0
+align_block=$((32 * 1024))
+fw_size=$(cat $firmware | wc -c)
+
+for size_hex in $(awk 'NR>1{print $2}' /proc/mtd); do
+	[ "$needle" -ge "$fw_size" ] && break
+
+	echo "mtd$mtd_num"
+	echo "----------"
+	partfile=/tmp/mtd${mtd_num}.bin
+
+	echo " Extracting block of $size_dec bytes starting at $needle"
+	size_dec=$((0x$size_hex))
+	dd if=$firmware of=$partfile bs=$align_block skip=$((needle/align_block)) count=$((size_dec/align_block))
+
+	echo " Flashing partition mtd${mtd_num}"
+	flashcp -v $partfile /dev/mtd${mtd_num}
+
+	rm $partfile
+	needle=$((needle + size_dec))
+	mtd_num=$((mtd_num + 1))
+	echo
+done
+}
+
+
 # Function to generate a backup directory
 generate_backup_dir() {
 	base_dir="/sdcard"
